### ISSUE TITLE
deprecated scaleform

### ISSUE THREAD

**Issue by MNoya** [funcdoor/LegionTD#12]
I checked the [custom_ui.txt](https://github.com/funcdoor/LegionTD/blob/master/game/dota_addons/legion_td/resource/flash3/custom_ui.txt) file and you don't seem to be using any scaleform module, yet [60% of your analyzed code comes from Valve's .as files](http://puu.sh/n17jF/58787be82d.png)

Go nuke those folders and never look back.

**Comment by funcdoor** [comment]
fixed
