### ISSUE TITLE
Lane creatures aggroing Summoned waiting creatures

### ISSUE THREAD

**Issue by SuricateCan** [funcdoor/LegionTD#16]
So, this is what happened today:

At round 26, there were many creatures in the summon wait area, waiting for the next round.
Meanwhile, the summoned creatures that were on the lane suddenly attracted the waiting creatures aggro, and they got stuck, and basically the game ended.

Here is a picture of it: http://steamcommunity.com/sharedfiles/filedetails/?id=642993249

Basically, they were trying to attack each other, but couldn't reach, so a stand off begun, and apparently never ended ;)

**Comment by funcdoor** [comment]
This issue has been fixed in the test version, steam workshop's ability to update dedi-enabled games has been broken for the last few days though

**Comment by SuricateCan** [comment]
Great to hear it (the fix part), but sad to hear it (the broken part).
